// XelerIA runtime patch v2.35-b
// Combos/Kits V2: cards compactas, nuevo combo con huérfanas y componentes buscables.
(function(){
  if(window.XELERIA_COMBOS_PATCH_V235)return;
  window.XELERIA_COMBOS_PATCH_V235=true;

  function q(id){return document.getElementById(id)}
  function e(v){return window.esc?window.esc(v):String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
  function st(id,msg,ok){if(window.setStatus)window.setStatus(id,msg,ok)}
  function fj(path,opt){return window.fetchJson(path,opt||{})}
  function mny(v){return window.money?window.money(v):(v?('$'+Math.round(Number(v||0)).toLocaleString('es-AR')):'')}
  function sid(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'_')}
  function short(v){let s=String(v||'');return s.length>22?s.slice(0,9)+'…'+s.slice(-7):s}
  function isSimple(x){let t=String(x?.item_type||'').toLowerCase();return x?.active!==false&&!['bundle','combo','kit'].includes(t)}
  function itemLabel(x){return `${x.sku||''} — ${x.name||''}${x.variant_name?' · '+x.variant_name:''}`.trim()}
  function marketOf(l){return String(l.marketplace||l.channel||'').toUpperCase()}

  function installStyle(){
    if(q('xeleriaCombosPatchStyle'))return;
    let s=document.createElement('style');s.id='xeleriaCombosPatchStyle';s.textContent='.iconMini{width:32px;height:32px;padding:0;border-radius:10px;display:inline-flex;align-items:center;justify-content:center;background:#fffaf0;border:1px solid #d8c89d;cursor:pointer}.iconMini.danger{background:#fff5f3;border-color:#d99;color:#9d1c13}.iconRow{display:flex;gap:6px;justify-content:flex-end}.comboHero{background:linear-gradient(135deg,#fffdf8,#efe3c5);border:1px solid var(--line);border-radius:22px;padding:16px;margin-bottom:14px}.comboCard{border:1px solid var(--line);border-radius:16px;background:#fff;padding:12px;margin-bottom:10px}.comboCard.pending{border-left:7px solid #b42318;background:#fff8f7}.comboCard.complete{border-left:7px solid #067647}.comboTop{display:grid;grid-template-columns:minmax(230px,1.2fr) minmax(220px,1fr) minmax(150px,.8fr) 78px;gap:10px;align-items:center}.comboTitle{font-weight:950}.comboMeta,.comboComp{font-size:12px;color:var(--muted)}.comboPills{display:flex;gap:6px;flex-wrap:wrap}.comboPanel{background:#fffaf0;border:1px solid #ead9ae;border-radius:18px;padding:16px;margin:12px 0}.compRow{display:grid;grid-template-columns:minmax(240px,1fr) 90px 74px;gap:8px;align-items:end;margin-top:7px}.suggestWrap{position:relative}.suggestBox{position:absolute;left:0;right:0;top:100%;z-index:90;background:#fff;border:1px solid #d8c89d;border-radius:12px;box-shadow:0 12px 28px rgba(0,0,0,.14);max-height:230px;overflow:auto;display:none}.suggestItem{padding:9px 10px;border-bottom:1px solid #f0e5c8;cursor:pointer}.suggestItem:hover{background:#fff7df}.suggestItem .sku{font-weight:950;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}.suggestItem .name{font-size:12px;color:var(--muted)}.orphanItem{display:grid;grid-template-columns:26px 58px minmax(180px,1fr) 90px;gap:8px;align-items:center;border:1px solid #eee2c8;border-radius:12px;background:#fff;padding:8px;margin-top:6px}.orphanItem input{width:18px;height:18px}@media(max-width:1100px){.comboTop{grid-template-columns:1fr}.compRow{grid-template-columns:1fr 80px 74px}.orphanItem{grid-template-columns:26px 52px 1fr}.orphanPrice{display:none}}';document.head.appendChild(s);
  }

  function shell(){
    let sec=q('combos');if(!sec)return;
    sec.innerHTML='<div class="comboHero"><div class="dashStatusLine"><div><h3>Gestión · Combos / Kits</h3><p>Definí la receta interna de cada combo. Sin componentes, el combo no descuenta stock real al venderse.</p></div><button class="primary" onclick="comboNewToggle()">Nuevo combo</button></div></div><div id="comboNewHost" data-open="0"></div><div class="card"><div class="dashStatusLine"><div><h3>Combos existentes</h3><p>Rojo: requiere componentes. Verde: composición definida. Blanco: sin cambios visuales.</p></div><button class="secondary" onclick="loadCombos()">Actualizar</button></div><div class="grid"><div class="col-8"><label>Buscar combo</label><input id="comboSearch" oninput="debouncedSearch(\'combo\')" placeholder="SKU, nombre o componente"></div><div class="col-2"><label>Mostrar</label><select id="comboLimit" onchange="loadCombos()"><option>20</option><option selected>50</option><option>100</option><option>200</option></select></div><div class="col-2"><label>&nbsp;</label><button onclick="loadCombos()">Buscar</button></div></div><div id="comboStatus" class="status"></div><div id="comboResults" style="margin-top:12px"></div></div>';
  }

  function addComponent(hostId,sku='',qty=1,label=''){
    let host=q(hostId);if(!host)return;
    let row=document.createElement('div');row.className='compRow compSourceRow';
    row.innerHTML='<div class="suggestWrap"><label>Componente</label><input class="compSkuText" placeholder="Buscar SKU o producto existente..." value="'+e(label||sku)+'" data-selected-sku="'+e(sku)+'" oninput="comboSearchComponent(this)" onfocus="comboSearchComponent(this)" autocomplete="off"><div class="suggestBox"></div></div><div><label>Cantidad</label><input class="compQty" type="number" step="0.01" value="'+e(qty||1)+'"></div><div><label>&nbsp;</label><div class="iconRow"><button class="iconMini" title="Editar" onclick="this.closest(\'.compRow\').querySelector(\'.compSkuText\').focus()">✎</button><button class="iconMini danger" title="Quitar" onclick="this.closest(\'.compRow\').remove()">&#128465;</button></div></div>';
    host.appendChild(row);
  }
  window.comboAddComponent=addComponent;

  window.comboSearchComponent=async function(input){
    let txt=(input.value||'').trim();input.dataset.selectedSku='';let box=input.closest('.suggestWrap')?.querySelector('.suggestBox');if(!box)return;
    if(txt.length<2){box.innerHTML='<div class="suggestItem"><div class="name">Escribí al menos 2 caracteres.</div></div>';box.style.display='block';return}
    box.innerHTML='<div class="suggestItem"><div class="name">Buscando...</div></div>';box.style.display='block';
    try{
      let d=await fj('/admin/inventory/search?q='+encodeURIComponent(txt)+'&limit=40&offset=0&include_listings=false');
      let items=(d.items||[]).filter(isSimple).slice(0,20);
      if(!items.length){box.innerHTML='<div class="suggestItem"><div class="name">Sin productos existentes para ese texto.</div></div>';return}
      box.innerHTML='';items.forEach(it=>{let div=document.createElement('div');div.className='suggestItem';div.innerHTML='<div class="sku">'+e(it.sku||'')+'</div><div class="name">'+e((it.name||'')+(it.variant_name?' · '+it.variant_name:''))+' · Stock: '+e(it.stock??0)+'</div>';div.addEventListener('mousedown',ev=>{ev.preventDefault();input.value=itemLabel(it);input.dataset.selectedSku=it.sku||'';box.style.display='none'});box.appendChild(div)});
    }catch(err){box.innerHTML='<div class="suggestItem"><div class="name">Error buscando productos.</div></div>'}
  };
  document.addEventListener('click',ev=>{if(!ev.target.closest('.suggestWrap'))document.querySelectorAll('.suggestBox').forEach(x=>x.style.display='none')});

  function collect(hostId){
    let rows=[...(q(hostId)?.querySelectorAll('.compSourceRow')||[])];let out=[];
    for(let r of rows){let sku=(r.querySelector('.compSkuText')?.dataset?.selectedSku||'').trim();let typed=(r.querySelector('.compSkuText')?.value||'').trim();let qty=Number(r.querySelector('.compQty')?.value||0);if(!sku&&typed)throw new Error('Elegí el componente desde la lista: '+typed);if(sku&&qty>0)out.push({component_sku:sku,quantity:qty})}
    return out;
  }

  window.comboSearchOrphans=async function(prefix){
    let market=q(prefix+'Market')?.value||'ML';let text=(q(prefix+'OrphanQ')?.value||'').trim();let lim=q(prefix+'OrphanLimit')?.value||100;let host=q(prefix+'Orphans');if(host)host.innerHTML='<div class="muted">Buscando huérfanas...</div>';
    try{
      let d=await fj('/admin/marketplace/unlinked?marketplace='+encodeURIComponent(market)+'&limit='+encodeURIComponent(lim)+'&q='+encodeURIComponent(text));
      window.comboOrphans=window.comboOrphans||{};window.comboOrphans[prefix]=d.items||[];
      let arr=window.comboOrphans[prefix];
      if(!host)return;
      if(!arr.length){host.innerHTML='<div class="dashEmpty">Sin publicaciones huérfanas para ese filtro.</div>';return}
      host.innerHTML=arr.map((x,i)=>'<label class="orphanItem"><input type="checkbox" data-idx="'+i+'"><span class="pill '+(String(x.marketplace).toUpperCase()==='ML'?'info':'ok')+'">'+e(x.marketplace)+'</span><span><strong>'+e(x.title||'')+'</strong><br><span class="small mono">'+e(short(x.external_product_id||''))+(x.external_variant_id?' / '+e(short(x.external_variant_id)):'')+' · SKU canal: '+e(x.seller_sku||'sin SKU')+'</span></span><span class="orphanPrice">'+mny(x.price)+'</span></label>').join('');
    }catch(err){if(host)host.innerHTML='<div class="status badtxt">Error buscando huérfanas: '+e(window.errText?window.errText(err):JSON.stringify(err))+'</div>'}
  };

  async function linkSelected(prefix,sku){
    let checks=[...(q(prefix+'Orphans')?.querySelectorAll('input[type="checkbox"]:checked')||[])];let arr=(window.comboOrphans&&window.comboOrphans[prefix])||[];
    for(let c of checks){let x=arr[Number(c.dataset.idx)];if(!x)continue;let body={sku:sku,marketplace:x.marketplace,external_product_id:x.external_product_id,external_variant_id:x.external_variant_id||'0',external_full_id:x.external_full_id||x.external_product_id,title:x.title||'',price:x.price??null,stock:x.stock??null,status:x.status||null,url:x.url||null,listing_type:x.listing_type||'standard',raw_data:x.raw_data||{},force:false};await fj('/admin/inventory/link-listing',{method:'POST',body:JSON.stringify(body)})}
    return checks.length;
  }

  window.comboNewToggle=function(){let h=q('comboNewHost');if(!h)return;if(h.dataset.open==='1'){h.dataset.open='0';h.innerHTML='';return}h.dataset.open='1';h.innerHTML='<div class="comboPanel"><h3>Nuevo combo</h3><div class="grid"><div class="col-3"><label>SKU combo nuevo</label><input id="newComboSku" placeholder="Ej: PCCOMBO..."></div><div class="col-5"><label>Nombre combo</label><input id="newComboName" placeholder="Nombre comercial"></div><div class="col-2"><label>Variante</label><input id="newComboVariant" placeholder="Opcional"></div><div class="col-2"><label>Categoría</label><input id="newComboCategory" value="COMBOS"></div><div class="col-12"><label>Descripción</label><input id="newComboDesc" placeholder="Opcional"></div></div><div class="dividerLine"></div><h3>Publicaciones ML/TN a asociar</h3><div class="grid"><div class="col-2"><label>Canal</label><select id="newComboMarket"><option>ML</option><option>TN</option></select></div><div class="col-7"><label>Buscar huérfanas</label><input id="newComboOrphanQ" placeholder="Título, SKU canal, publicación"></div><div class="col-1"><label>Límite</label><select id="newComboOrphanLimit"><option>50</option><option selected>100</option><option>200</option></select></div><div class="col-2"><label>&nbsp;</label><button class="secondary" onclick="comboSearchOrphans(\'newCombo\')">Buscar</button></div></div><div id="newComboOrphans"></div><div class="dividerLine"></div><h3>Componentes</h3><div id="newComboComponents"></div><div class="btnrow" style="margin-top:10px"><button class="secondary" onclick="comboAddComponent(\'newComboComponents\')">Agregar otro</button><button class="ok" onclick="comboCreate()">Crear combo</button><button class="secondary" onclick="comboNewToggle()">Cerrar</button></div><div id="newComboStatus" class="status"></div></div>';addComponent('newComboComponents');};

  window.comboCreate=async function(){let sku=(q('newComboSku')?.value||'').trim();let name=(q('newComboName')?.value||'').trim();if(!sku||!name){st('newComboStatus','SKU y nombre son obligatorios.',false);return}let comps=[];try{comps=collect('newComboComponents')}catch(err){st('newComboStatus',err.message,false);return}if(!comps.length){st('newComboStatus','Agregá al menos un componente.',false);return}let body={sku:sku,name:name,variant_name:q('newComboVariant')?.value||null,category:q('newComboCategory')?.value||'COMBOS',description:q('newComboDesc')?.value||null,active:true,components:comps};st('newComboStatus','Creando combo...');try{await fj('/admin/inventory/create-bundle',{method:'POST',body:JSON.stringify(body)});let linked=await linkSelected('newCombo',sku);st('newComboStatus','Combo creado. Publicaciones vinculadas: '+linked,true);if(window.loadCombos)await window.loadCombos()}catch(err){st('newComboStatus','Error creando combo: '+e(window.errText?window.errText(err):JSON.stringify(err)),false)}};

  function listingPills(item){let arr=Array.isArray(item.listings)?item.listings:[];if(!arr.length)return '<span class="muted">Sin publicaciones vinculadas.</span>';return '<div class="comboPills">'+arr.map(l=>'<span class="pill '+(marketOf(l)==='ML'?'info':'ok')+'">'+e(marketOf(l))+' · '+e(short(l.external_product_id||l.listing_id||''))+(l.external_variant_id?':'+e(short(l.external_variant_id)):'')+'</span>').join('')+'</div>'}
  async function paintCard(item,idx){let card=q('comboCard_'+idx);if(!card)return;try{let d=await fj('/admin/bundles/'+encodeURIComponent(item.sku),{skipLastJson:true});let comps=d.components||[];card.classList.remove('pending','complete');card.classList.add(comps.length?'complete':'pending');let pill=q('comboState_'+idx);if(pill){pill.className='pill '+(comps.length?'ok':'bad');pill.textContent=comps.length?'Completo':'Sin componentes'}let c=q('comboComp_'+idx);if(c)c.innerHTML=comps.length?comps.slice(0,4).map(x=>e(x.component_sku||'')+' × '+e(x.quantity||1)).join('<br>')+(comps.length>4?'<br><span class="small">+'+(comps.length-4)+' más</span>':''):'Requiere definir composición'}catch(err){let c=q('comboComp_'+idx);if(c)c.textContent='No pude leer composición'}}

  window.renderCombos=function(){let host=q('comboResults');if(!host)return;let items=(window.state&&state.comboItems)||[];if(!items.length){host.innerHTML='<div class="dashEmpty">Sin combos para este filtro.</div>';return}host.innerHTML=items.map((it,idx)=>'<div class="comboCard" id="comboCard_'+idx+'"><div class="comboTop"><div><div class="comboTitle mono">'+e(it.sku||'')+'</div><div>'+e(it.name||'')+'</div><div class="comboMeta">'+e(it.category||'COMBOS')+' · stock calculado: <strong>'+e(it.stock??0)+'</strong></div></div><div>'+listingPills(it)+'</div><div><span id="comboState_'+idx+'" class="pill warn">Revisando</span><div id="comboComp_'+idx+'" class="comboComp">Leyendo composición...</div></div><div class="iconRow"><button class="iconMini" title="Editar" onclick="comboEdit('+idx+')">✎</button><button class="iconMini danger" title="Eliminar" onclick="deleteInventoryItem('+idx+')">&#128465;</button></div></div><div id="comboEdit_'+sid(it.sku)+'"></div></div>').join('');items.forEach((it,idx)=>paintCard(it,idx));};

  window.comboEdit=async function(idx){let item=(window.state&&state.comboItems&&state.comboItems[idx])||null;if(!item)return;let host=q('comboEdit_'+sid(item.sku));if(!host)return;if(host.dataset.open==='1'){host.dataset.open='0';host.innerHTML='';return}document.querySelectorAll('[id^="comboEdit_"]').forEach(x=>{x.dataset.open='0';x.innerHTML=''});host.dataset.open='1';host.innerHTML='<div class="comboPanel"><h3>Modificar combo</h3><div class="grid"><div class="col-3"><label>SKU</label><input id="editComboSku" value="'+e(item.sku||'')+'" disabled></div><div class="col-5"><label>Nombre</label><input id="editComboName" value="'+e(item.name||'')+'"></div><div class="col-2"><label>Estado</label><select id="editComboActive"><option value="true" '+(item.active!==false?'selected':'')+'>Activo</option><option value="false" '+(item.active===false?'selected':'')+'>Inactivo</option></select></div><div class="col-2"><label>Variante</label><input id="editComboVariant" value="'+e(item.variant_name||'')+'"></div><div class="col-4"><label>Categoría</label><input id="editComboCategory" value="'+e(item.category||'COMBOS')+'"></div><div class="col-8"><label>Descripción</label><input id="editComboDesc" value="'+e(item.description||'')+'"></div></div><div class="dividerLine"></div><h3>Componentes</h3><div id="editComboComponents"></div><div class="btnrow" style="margin-top:10px"><button class="secondary" onclick="comboAddComponent(\'editComboComponents\')">Agregar otro</button><button class="ok" onclick="comboSave('+idx+')">Guardar combo</button><button class="secondary" onclick="comboEdit('+idx+')">Cerrar</button></div><div id="editComboStatus" class="status">Cargando composición...</div></div>';try{let d=await fj('/admin/bundles/'+encodeURIComponent(item.sku));let comps=d.components||[];if(!comps.length)addComponent('editComboComponents');else comps.forEach(c=>addComponent('editComboComponents',c.component_sku||'',c.quantity||1,c.component_label||c.component_sku||''));st('editComboStatus','Composición cargada: '+comps.length+' componente(s).',true)}catch(err){addComponent('editComboComponents');st('editComboStatus','No pude cargar composición: '+e(window.errText?window.errText(err):JSON.stringify(err)),false)}setTimeout(()=>host.scrollIntoView({behavior:'smooth',block:'start'}),60)};

  window.comboSave=async function(idx){let item=(window.state&&state.comboItems&&state.comboItems[idx])||null;if(!item)return;let comps=[];try{comps=collect('editComboComponents')}catch(err){st('editComboStatus',err.message,false);return}if(!comps.length){st('editComboStatus','El combo debe tener al menos un componente.',false);return}let body={sku:item.sku,name:q('editComboName')?.value||'',variant_name:q('editComboVariant')?.value||'',category:q('editComboCategory')?.value||'COMBOS',description:q('editComboDesc')?.value||'',active:q('editComboActive')?.value==='true',components:comps};st('editComboStatus','Guardando combo...');try{await fj('/admin/inventory/update-bundle',{method:'POST',body:JSON.stringify(body)});st('editComboStatus','Combo actualizado.',true);if(window.loadCombos)await window.loadCombos()}catch(err){st('editComboStatus','Error guardando combo: '+e(window.errText?window.errText(err):JSON.stringify(err)),false)}};

  function patchShowView(){if(window._xeleriaShowViewCombosPatch)return;window._xeleriaShowViewCombosPatch=window.showView;window.showView=function(id){let r=window._xeleriaShowViewCombosPatch.apply(this,arguments);if(id==='combos'){shell();setTimeout(()=>window.loadCombos&&window.loadCombos(),40)}return r}}
  function init(){installStyle();patchShowView();if(q('combos')?.classList.contains('active')){shell();if(window.loadCombos)window.loadCombos()}console.info('XelerIA combos patch v2.35 loaded')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
